### ISSUE TITLE
Type is obfuscated for non-test APK only

### ISSUE THREAD

**Issue by lwasyl** [slackhq/keeper#108]
**Keeper version:** 0.12.0

We've updated `androidx.test` dependencies recently, and we started seeing `ClassNotFound` exceptions:
```java
java.lang.NoSuchMethodError: No static method getFuture(Landroidx/concurrent/futures/CallbackToFutureAdapter$Resolver;)Lcom/google/common/util/concurrent/ListenableFuture; in class Landroidx/concurrent/futures/CallbackToFutureAdapter; or its super classes (declaration of 'androidx.concurrent.futures.CallbackToFutureAdapter' appears in base.apk)
at androidx.test.core.app.ListFuture.<init>(ListFuture.java:72)
at androidx.test.core.app.DeviceCapture$forceRedrawGlobalWindowViews$1.run(DeviceCapture.kt:168)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

I investigated and this is what I observe:

*tested apk* will have return type of a method in 3rd party library (`concurrent-futures`) obfuscated:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3951580/201947026-a2e599de-a202-4e0f-b5f3-4b792af99953.png">
(the `androidx.appcompat.widget` comes from obfuscation relocation config)

*test apk* will have return type of that method _not_ obfuscated:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/3951580/201947306-fe22ce0d-a3e0-4e42-a29a-1da119dcc733.png">

In `build/intermediates/<testBuildType>AndroidTest/inferredKeepRules.pro` I can see a keep rule for that type:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/3951580/201947513-5014fb47-38e4-4ed5-bf6b-bd85554aca61.png">

I'm not sure exactly but it looks like a bug? Iiuc Keeper should wire stuff such that the inferred keep rule is applied to the tested apk, which seems to not be the case. 

Could it be caused by the fact that the offending code path is only triggered on FTL? I'm not 100% sure it's the case, but I don't reproduce the issue locally. In any case, I'd still expect that the inferred rules are applied to the tested APK — should I?

**Comment by ZacSweers** [comment]
I've read through this a few times and I don't really understand your setup. Can you link a minimally reproducing sample (preferably using Keeper's own tests/sample)?

I'm particularly confused by "obfuscation relocation config" - is that R8, proguard, shadowing?

**Comment by ZacSweers** [comment]
Closing due to lack of response

**Comment by TWiStErRob** [comment]
I guess if there's a repro, you would revisit it :)

**Comment by oheyadam** [comment]
Hm, I'm seeing this issue as well after updating to the latest version of Compose (1.4). I'm on v 0.13.0 of Keeper, and seeing this stacktrace on CI:

```
java.lang.NoSuchMethodError: No static method getFuture(Landroidx/concurrent/futures/CallbackToFutureAdapter$Resolver;)Lcom/google/common/util/concurrent/ListenableFuture; in class Landroidx/concurrent/futures/CallbackToFutureAdapter; or its super classes (declaration of 'androidx.concurrent.futures.CallbackToFutureAdapter' appears in /data/app/com.travelperk.staging-FAClNwqor78d0WjMntn_Hw==/base.apk)
at androidx.test.core.app.ListFuture.<init>(ListFuture.java:72)
at androidx.test.core.app.DeviceCapture$forceRedrawGlobalWindowViews$1.run(DeviceCapture.kt:168)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7263)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

It kinda makes no sense because when I SSH into the CI machine, I can see the following rules in my `inferredKeepRules.pro` file 🤔 

```
-keep class androidx.concurrent.futures.AbstractResolvableFuture {
  public void addListener(java.lang.Runnable,java.util.concurrent.Executor);
  public java.lang.Object get(long,java.util.concurrent.TimeUnit);
  public boolean isCancelled();
}
-keep class androidx.concurrent.futures.CallbackToFutureAdapter {
  public static com.google.common.util.concurrent.ListenableFuture getFuture(androidx.concurrent.futures.CallbackToFutureAdapter$Resolver);
}
-keep class androidx.concurrent.futures.CallbackToFutureAdapter$Completer {
  public boolean set(java.lang.Object);
  public boolean setException(java.lang.Throwable);
}
-keep interface androidx.concurrent.futures.CallbackToFutureAdapter$Resolver {
  public java.lang.Object attachCompleter(androidx.concurrent.futures.CallbackToFutureAdapter$Completer);
}
-keep class androidx.concurrent.futures.ResolvableFuture {
  public static androidx.concurrent.futures.ResolvableFuture create();
  public boolean set(java.lang.Object);
  public boolean setException(java.lang.Throwable);
  public boolean setFuture(com.google.common.util.concurrent.ListenableFuture);
}
```

@lwasyl, what did you end up doing?

**Comment by lwasyl** [comment]
@oheyadam This looks very similar to my case, I also see appropriate inferred rules.

I ended up staying on older Espresso and Keeper 0.12.0 for now, so I don't have a solution for this issue. If you find one, I'm interested!

**Comment by TWiStErRob** [comment]
Can either of you create a [repro](https://github.com/slackhq/keeper/issues/108#issuecomment-1343431270)?, because then this could be investigated and fixed.

**Comment by TWiStErRob** [comment]
Btw, we had a similar issue in the past, not with Keeper, but with `ListenableFuture` vs work-manager.

What we found is that the `androidTest.apk` won't contain any duplicate _dependencies_ that exist in the `app.apk`, but may contain duplicate _classes_ if they're in different dependencies. Because Guava was messing about and extracting `listenablefuture` to its own library, on some versions it's still in `guava` library and on some it's not. AGP can't figure out that these are the "same", so it packages things in both APKs from the different dependencies. We tried many different workarounds, but the only one that was acceptable production code and actually working is to keep the exact same signature in both APKs.

@lwasyl @oheyadam So in your case you would probably need to make sure that the offending function has the exact same signature in both APKs by manually keeping the name of `com.google.common.util.concurrent.ListenableFuture` (`-keepnames class ...`).

@ZacSweers I suspect that Keeper has the same dilemma, not knowing internally that `guava>com.google.common.util.concurrent.ListenableFuture` and `listablefuture>com.google.common.util.concurrent.ListenableFuture` are the same.

**Comment by TWiStErRob** [comment]
I think it is the same, and considering the promise of "Keeper":
> A Gradle plugin that infers Proguard/R8 keep rules for androidTest sources.

it should handle this special case somehow, as it clearly comes up in probably all projects using obfuscated test APKs.
